---
commit-msg:
  commands:
    commitlint:
      run: npx --yes commitlint --config .commitlint.config.js --edit
pre-commit:
  parallel: true
  commands:
    hadolint:
      tags: lint docker
      glob: "Dockerfile*"
      run: hadolint {staged_files} --failure-threshold warning
    prettier:
      tags: style glue
      glob: "*.{md,yaml,yml}"
      run: prettier --check {staged_files}
    shellcheck:
      tags: lint shell
      glob: "*.{bash,sh}"
      run: shellcheck {staged_files}
    shfmt:
      tags: style shell
      glob: "*.{bash,sh}"
      run: shfmt -d {staged_files}
    yamllint:
      tags: lint yaml
      glob: "*.{yaml,yml}"
      run: |
        yamllint -d "{extends: default, rules: {line-length: {max: 120}, comments: disable}}" {staged_files}
